CREATE TABLE student (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    surname VARCHAR2(255),
    name VARCHAR2(255),
    patronymic VARCHAR2(255),
    birth_date DATE,
    phone VARCHAR2(20),
    email VARCHAR2(255),
    git VARCHAR2(255),
    telegram VARCHAR2(50)
);